language: R

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev
  - R -e 'install.packages(c("devtools", "testthat","tidyverse"))'
  
cache:
  packages: true

install:
  - R -e 'getwd()'

script:
  - Rscript ./tests/run_test.R
